config/routes.rb
Rails.application.routes.draw do

  get 'users/new', to:'users#new'
  get 'users/show', to:'users#show'
  post 'users/create', to:'users#create'

  get 'blogs/blog', to:'blogs#blog'
  get 'blogs/blog_single', to:'blogs#blog_single'

  post 'sessions/login', to:'sessions#login'
  delete 'sessions/destroy', to:'sessions#destroy'

  get 'shops/shop', to:'shops#shop'
  get 'shops/product_details', to:'shops#product_details'
  get 'shops/cart', to:'shops#cart'
  get 'shops/checkout', to:'shops#checkout'

  root 'welcome#home'
  get 'welcome/home', to:'welcome#home'
  get 'welcome/contact', to:'welcome#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user

    def current_user
    	@current_user ||= User.find_by(id: session[:user_id])
    end

	def logged_in?
    	redirect_to root_url unless current_user.blank?
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def blog
  end

  def blog_single
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :logged_in?, only: [:destroy]

  def login
    @user = User.find_by(email: params[:email])
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url
    else
      redirect_to users_new_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  private

  def user_params
    params.permit(:email, :password)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    def shop
    end

    def product_details
    end

    def cart
    end

    def checkout
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: :new#, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
    render layout: "session"
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to welcome_home_path
    else
      render 'new'
    end
  end

  private

  # def set_user
    # @user = User.find(params[:id])
  # end

  def user_params
    params.permit(:name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/blog.html.erb
<section>
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="left-sidebar">
                <h2>Category</h2>
                <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
                                    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                    Sportswear
                                </a>
                            </h4>
                        </div>
                        <div id="sportswear" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul>
                                    <li><a href="">Nike </a></li>
                                    <li><a href="">Under Armour </a></li>
                                    <li><a href="">Adidas </a></li>
                                    <li><a href="">Puma</a></li>
                                    <li><a href="">ASICS </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordian" href="#mens">
                                    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                    Mens
                                </a>
                            </h4>
                        </div>
                        <div id="mens" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul>
                                    <li><a href="">Fendi</a></li>
                                    <li><a href="">Guess</a></li>
                                    <li><a href="">Valentino</a></li>
                                    <li><a href="">Dior</a></li>
                                    <li><a href="">Versace</a></li>
                                    <li><a href="">Armani</a></li>
                                    <li><a href="">Prada</a></li>
                                    <li><a href="">Dolce and Gabbana</a></li>
                                    <li><a href="">Chanel</a></li>
                                    <li><a href="">Gucci</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordian" href="#womens">
                                    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                    Womens
                                </a>
                            </h4>
                        </div>
                        <div id="womens" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul>
                                    <li><a href="">Fendi</a></li>
                                    <li><a href="">Guess</a></li>
                                    <li><a href="">Valentino</a></li>
                                    <li><a href="">Dior</a></li>
                                    <li><a href="">Versace</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="#">Kids</a></h4>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="#">Fashion</a></h4>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="#">Households</a></h4>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="#">Interiors</a></h4>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="#">Clothing</a></h4>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="#">Bags</a></h4>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="#">Shoes</a></h4>
                        </div>
                    </div>
                </div><!--/category-products-->
            
                <div class="brands_products"><!--brands_products-->
                    <h2>Brands</h2>
                    <div class="brands-name">
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                            <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                            <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                            <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                            <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                            <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                            <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                        </ul>
                    </div>
                </div><!--/brands_products-->
                
                <div class="price-range"><!--price-range-->
                    <h2>Price Range</h2>
                    <div class="well">
                         <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                         <b>$ 0</b> <b class="pull-right">$ 600</b>
                    </div>
                </div><!--/price-range-->
                
                <div class="shipping text-center"><!--shipping-->
                    <%= image_tag("home/shipping.jpg", alt: "") %>
                </div><!--/shipping-->
            </div>
        </div>
        <div class="col-sm-9">
            <div class="blog-post-area">
                <h2 class="title text-center">Latest From our Blog</h2>
                <div class="single-blog-post">
                    <h3>Girls Pink T Shirt arrived in store</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-user"></i> Mac Doe</li>
                            <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                            <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                        </ul>
                        <span>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-half-o"></i>
                        </span>
                    </div>
                    <a href=""><%= image_tag("blog/blog-one.jpg", alt: "") %></a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <a  class="btn btn-primary" href="">Read More</a>
                </div>
                <div class="single-blog-post">
                    <h3>Girls Pink T Shirt arrived in store</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-user"></i> Mac Doe</li>
                            <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                            <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                        </ul>
                        <span>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                        </span>
                    </div>
                    <a href=""><%= image_tag("blog/blog-two.jpg", alt: "") %></a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <a  class="btn btn-primary" href="">Read More</a>
                </div>
                <div class="single-blog-post">
                    <h3>Girls Pink T Shirt arrived in store</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-user"></i> Mac Doe</li>
                            <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                            <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                        </ul>
                        <span>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                        </span>
                    </div>
                    <a href=""><%= image_tag("blog/blog-three.jpg", alt: "") %></a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <a  class="btn btn-primary" href="">Read More</a>
                </div>
                <div class="pagination-area">
                    <ul class="pagination">
                        <li><a href="" class="active">1</a></li>
                        <li><a href="">2</a></li>
                        <li><a href="">3</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

app/views/layouts/_bottom_footer.html.erb
<div class="footer-bottom">
<div class="container">
    <div class="row">
        <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
        <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
    </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer"><!--Footer-->
<div class="footer-top">
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <div class="companyinfo">
                    <h2><span>e</span>-shopper</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                </div>
            </div>
            <div class="col-sm-7">
                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <%= image_tag("home/iframe1.png") %>
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>
                
                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <%= image_tag("home/iframe2.png") %>
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>
                
                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <%= image_tag("home/iframe3.png") %>
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>
                
                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <%= image_tag("home/iframe4.png") %>
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="address">
                    <%= image_tag("home/map.png") %>
                    <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer-widget">
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Service</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Online Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Order Status</a></li>
                        <li><a href="#">Change Location</a></li>
                        <li><a href="#">FAQ’s</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Quock Shop</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">T-Shirt</a></li>
                        <li><a href="#">Mens</a></li>
                        <li><a href="#">Womens</a></li>
                        <li><a href="#">Gift Cards</a></li>
                        <li><a href="#">Shoes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Policies</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privecy Policy</a></li>
                        <li><a href="#">Refund Policy</a></li>
                        <li><a href="#">Billing System</a></li>
                        <li><a href="#">Ticket System</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>About Shopper</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Store Location</a></li>
                        <li><a href="#">Affillate Program</a></li>
                        <li><a href="#">Copyright</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3 col-sm-offset-1">
                <div class="single-widget">
                    <h2>About Shopper</h2>
                    <form action="#" class="searchform">
                        <input type="text" placeholder="Your email address" />
                        <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                        <p>Get the most recent updates from <br />our site and be updated your self...</p>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

</footer><!--/Footer-->

app/views/layouts/_header.html.erb
<div class="header-middle"><!--header-middle-->
    <div class="container">
        <div class="row">
            <div class="col-md-4 clearfix">
                <div class="logo pull-left">
                    <%= link_to image_tag("home/logo.png"), welcome_home_path %>
                </div>
                <div class="btn-group pull-right clearfix">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                            USA
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="">Canada</a></li>
                            <li><a href="">UK</a></li>
                        </ul>
                    </div>
                    
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                            DOLLAR
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="">Canadian Dollar</a></li>
                            <li><a href="">Pound</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-8 clearfix">
                <div class="shop-menu clearfix pull-right">
                    <ul class="nav navbar-nav">
                        <li><%= link_to "<i class='fa fa-user'></i> Account".html_safe, users_show_path %></li>
                        <li><a href=""><i class="fa fa-star"></i> Wishlist</a></li>
                        <li><%= link_to "<i class='fa fa-crosshairs'></i> Checkout".html_safe, shops_checkout_path %></li>
                        <li><%= link_to "<i class='fa fa-shopping-cart'></i> Cart".html_safe, shops_cart_path %></li> 
                        <li><% if current_user.present? %>
                                <%= link_to "<i class='fa fa-unlock'></i> Logout".html_safe, sessions_destroy_path, method: :delete %>
                            <% else %>
                                <%= link_to "<i class='fa fa-lock'></i> Login".html_safe, users_new_path %>
                            <% end %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div><!--/header-middle-->

<div class="header-bottom"><!--header-bottom-->
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="mainmenu pull-left">
                    <ul class="nav navbar-nav collapse navbar-collapse">
                        <li><%= link_to "Home", welcome_home_path, class: "active" %></li>
                        <li class="dropdown"><%= link_to "<i class='fa fa-angle-down'></i> Shop".html_safe, shops_shop_path %>
                            <ul role="menu" class="sub-menu">
                                <li><%= link_to 'Products', shops_shop_path %></li>
                                <li><%= link_to 'Checkout', shops_checkout_path %></li> 
                                <li><%= link_to 'Cart', shops_cart_path %></li> 
                                <li><%= link_to 'Login', users_new_path %></li> 
                            </ul>
                        </li> 
                        <li class="dropdown"><%= link_to "<i class='fa fa-angle-down'></i> Blog".html_safe, shops_shop_path %>
                            <ul role="menu" class="sub-menu">
                                <li><%= link_to 'Blog List', blogs_blog_path %></li>
                                <li><%= link_to 'Blog Single', blogs_blog_single_path %></li>
                            </ul>
                        </li> 
                        <li><%= link_to 'Contact', welcome_contact_path %></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="search_box pull-right">
                    <input type="text" placeholder="Search"/>
                </div>
            </div>
        </div>
    </div>
</div><!--/header-bottom-->
</header><!--/header-->

app/views/layouts/_top_header.html.erb
<header id="header"><!--header-->
<div class="header_top"><!--header_top-->
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="contactinfo">
                    <ul class="nav nav-pills">
                        <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="social-icons pull-right">
                    <ul class="nav navbar-nav">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div><!--/header_top-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>E-Shopper</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/top_header' %>
    <%= render 'layouts/header' %>
    
    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= render 'layouts/bottom_footer' %>

  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>E-Shopper</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/top_header' %>
    
    <%= yield %>

    <%= render 'layouts/bottom_footer' %>

  </body>
</html>

app/views/users/new.html.erb
<section id="form"><!--form-->
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-sm-offset-1">
				<div class="login-form"><!--login form-->
					<h2>Login to your account</h2>
					<%= form_with(url: sessions_login_path, method: "post", local: true) do |form| %>
					
						<%= form.email_field :email, placeholder: "Email Address" %>

						<%= form.password_field :password, placeholder: "Password" %>
						<span>
							<%= check_box_tag :remember_me, true, params[:remember_me] %> 
							Keep me signed in
						</span>
						<button type="submit" class="btn btn-default">Login</button>
						
					<% end %>
				</div><!--/login form-->
			</div>
			<div class="col-sm-1">
				<h2 class="or">OR</h2>
			</div>
			<div class="col-sm-4">
				<div class="signup-form"><!--sign up form-->
					<h2>New User Signup!</h2>
					
					<%= form_with(url: users_create_path, method: "post", local: true) do |form| %>
							<%= form.text_field :name, placeholder: "Name" %>
						
							<%= form.email_field :email, placeholder: "Email Address" %>

							<%= form.password_field :password, placeholder: "Password" %>

							<button type="submit" class="btn btn-default">Signup</button>
					<% end %>

				</div><!--/sign up form-->
			</div>
		</div>
	</div>
</section><!--/form-->

app/views/users/show.html.erb
<div id="account-page" class="container">
    <h2 class="title text-center">My Account</h2>
    <div id="account-detail" class="container">
        <div class="row">
            <div class="col-xs-12 col-lg-4">
                <p class="user_detail">Email</p>
                <p><%= current_user.email %></p>
            </div>
            <div class="col-xs-12 col-lg-8 mt-sm-5 mt-lg-0 ">
                <p class="user_detail">Add new address</p>
                <div class="row">
                    <div class="col-xs-12 col-lg-6">
                        <p><%= current_user.name %></p>
                        <p>My Address</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h2 class="title text-center">My Order</h2>
</div>